server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: Identifier

  datasource:
    url: jdbc:postgresql://localhost:5433/coworking_reservation
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
